### ISSUE TITLE
GSEControl creation is not schema valid/correct

### ISSUE THREAD

**Issue by danyill** [JakobVogelsang/oscd-publisher#9]
Thank you for this plugin. I have done a little recent testing.

I tried to create a new `GSEControl` and the output is in the attached file:

[Test_GSEControl.zip](https://github.com/JakobVogelsang/oscd-publisher/files/13210747/Test_GSEControl.zip)

![image](https://github.com/JakobVogelsang/oscd-publisher/assets/674783/89a5f83e-f815-4412-9300-82a429ed1812)

I noticed an issue with the `GSEControl`:

```xml

<GSEControl name="newGSEControl_001" confRev="10001" type="GOOSE" appId="XAT_2202_M1&gt;&gt;LD0&gt;newGSEControl_001" datSet="newDataSet_001x" appID="hey"/>
```

The `appId` is there twice, one appears to be an identity string.

The identity string should not be there at all (i.e. the following attribute should be removed: `appId="XAT_2202_M1&gt;&gt;LD0&gt;newGSEControl_001"`)

**Comment by JakobVogelsang** [comment]
I am sorry this was a version conflict on scl-editor. It should work now. Can you confirm?
